### ISSUE TITLE
Failed to setup hyprland headers

### ISSUE THREAD

**Issue by Magnitudexx** [Duckonaut/hyprload#23]
Building Hyprland from source and have build the latest hyprland and hyprload. When i try to install plugins I get the error failed to setup hyprland header and dont now what to do. Does someone have some debug steps?

**Comment by Duckonaut** [comment]
Hyprland just updated and completely changed the build process. You can expect a fix over the weekend

**Comment by Magnitudexx** [comment]
ok

**Comment by Duckonaut** [comment]
Should be fixed as of 8a727508c9edda5e2562c7d7e7967bef4a7bdfa1

**Comment by Schmazda** [comment]
This error still occurs. I am using Arch Linux and installed hyprland via `yay -S hyprland-git`

**Comment by TomAintAround** [comment]
> This error still occurs. I am using Arch Linux and installed hyprland via `yay -S hyprland-git`

Same. Currently my package version is hyprland-git 0.32.0.r0.751d2851-1
