### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shadowelite-sec** [Duckonaut/hyprload#8]
I am facing this error when i try to install hyprload

```
curl -sSL https://raw.githubusercontent.com/Duckonaut/hyprload/main/install.sh 
| bash
[1/7] Cloning hyprload to /home/shadow/.local/share/hyprload/src
Already up to date.
[2/7] Cloned hyprload source to /home/shadow/.local/share/hyprload/src
[3/7] Setting up hyprland source in /home/shadow/.local/share/hyprload/hyprland
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

HEAD is now at 7fde80f3 layers: fix wonky focus on multimon
[4/7] Set up hyprland source in /home/shadow/.local/share/hyprload/hyprland at commit 7fde80f38eefef4ec1e682947c4ae152aa0974db
[5/7] Setting up hyprland plugin environment
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/make' as the super user
Authenticating as: shadow
Password: 
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
[6/7] Installing hyprload
make: Entering directory '/home/shadow/.local/share/hyprload/src'
Hyprland headers not available. Run `make pluginenv` in the root Hyprland directory.
make: *** [Makefile:45: check_env] Error 1
make: Leaving directory '/home/shadow/.local/share/hyprload/src'
[7/7] Installed hyprload!
```

i already run `make pluginenv` many times but still getting the same error 

![20230503_12h59m10s_grim](https://github.com/Duckonaut/hyprload/assets/54718375/1b72706a-45e9-48b1-8194-b470febbe38c)

**Comment by Duckonaut** [comment]
Can you give me the output of `pkg-config --cflags hyprland`? Also check if you have the directory `/usr/local/include/wlr`

**Comment by shadowelite-sec** [comment]
> Can you give me the output of `pkg-config --cflags hyprland`? Also check if you have the directory `/usr/local/include/wlr`

![20230510_19h48m45s_grim](https://github.com/Duckonaut/hyprload/assets/54718375/6f586dfe-3a6c-4fed-89b2-d777c0ab610b)

inside `/usr/local/include/hyprland/wlroots/wlr`

![20230510_19h54m12s_grim](https://github.com/Duckonaut/hyprload/assets/54718375/23b107c9-3d3a-430d-b54c-f023422ee6f6)

also inside wlr there is no `config.h`

**Comment by Duckonaut** [comment]
Tested locally, something's up with upstream Hyprland. Will update the issue when i know what's going on.

**Comment by 7832ru** [comment]
@shadowelite-sec i was having the same problem and just solved it by installing wlroots (for some reason I didn't have it)

**Comment by Duckonaut** [comment]
That should work but Hyprland bundles its own wlroots so it shouldn't be required long term. It's a temporary fix though

**Comment by shadowelite-sec** [comment]
> Tested locally, something's up with upstream Hyprland. Will update the issue when i know what's going on.

Oh ok 👍

**Comment by shadowelite-sec** [comment]
> @shadowelite-sec i was having the same problem and just solved it by installing wlroots (for some reason I didn't have it)

Yes, the compilation was successful. However, when I try to run the `$HOME/.local/share/hyprload/hyprload.sh` , Hyprland crashes.

<details><summary>Crash Report</summary><blockquote>
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Calm down, it was a misinput! MISINPUT!

Hyprland received signal 11 (Segmentation fault)

Version: f2725a374a5921903bf918fdfd8111b537cbf18f

Hyprland seems to be running with plugins. This crash might not be Hyprland's fault.
Plugins:
	 () 


System info:
	System name: Linux
	Node name: elite
	Release: 6.3.1-arch2-1
	Version: #1 SMP PREEMPT_DYNAMIC Wed, 10 May 2023 08:54:47 +0000

GPU:
	00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] [10de:1f95] (rev a1) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x78e) [0x55fbd42590ee]
		??
		??:0
	#1 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x55fbd41f4cdc]
		??
		??:0
	#2 | /usr/lib/libc.so.6(+0x39ab0) [0x7f633dd62ab0]
		??
		??:0
	#3 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNKSt8_Rb_treeIN4toml2v33keyESt4pairIKS2_St10unique_ptrINS1_4nodeESt14default_deleteIS6_EEESt10_Select1stISA_ESt4lessIvESaISA_EE8_M_beginEv+0xc) [0x7f632816641a]
		??
		??:0
	#4 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNKSt8_Rb_treeIN4toml2v33keyESt4pairIKS2_St10unique_ptrINS1_4nodeESt14default_deleteIS6_EEESt10_Select1stISA_ESt4lessIvESaISA_EE17_M_lower_bound_trISt17basic_string_viewIcSt11char_traitsIcEEvEESt23_Rb_tree_const_iteratorISA_ERKT_+0x2c) [0x7f6328163ff2]
		??
		??:0
	#5 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNKSt8_Rb_treeIN4toml2v33keyESt4pairIKS2_St10unique_ptrINS1_4nodeESt14default_deleteIS6_EEESt10_Select1stISA_ESt4lessIvESaISA_EE10_M_find_trISt17basic_string_viewIcSt11char_traitsIcEEvEESt23_Rb_tree_const_iteratorISA_ERKT_+0x33) [0x7f632816011b]
		??
		??:0
	#6 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNSt8_Rb_treeIN4toml2v33keyESt4pairIKS2_St10unique_ptrINS1_4nodeESt14default_deleteIS6_EEESt10_Select1stISA_ESt4lessIvESaISA_EE10_M_find_trISt17basic_string_viewIcSt11char_traitsIcEEvEESt17_Rb_tree_iteratorISA_ERKT_+0x3a) [0x7f6328160062]
		??
		??:0
	#7 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNSt3mapIN4toml2v33keyESt10unique_ptrINS1_4nodeESt14default_deleteIS4_EESt4lessIvESaISt4pairIKS2_S7_EEE4findISt17basic_string_viewIcSt11char_traitsIcEEEEDTcldtdtdefpT4_M_t10_M_find_trfp_EERKT_+0x23) [0x7f63281584e7]
		??
		??:0
	#8 | /home/shadow/.local/share/hyprload/hyprload.so(_ZN4toml2v35table3getESt17basic_string_viewIcSt11char_traitsIcEE+0x46) [0x7f63281479ce]
		??
		??:0
	#9 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNK4toml2v35table8containsESt17basic_string_viewIcSt11char_traitsIcEE+0x5e) [0x7f6328146e3e]
		??
		??:0
	#10 | /home/shadow/.local/share/hyprload/hyprload.so(_ZN8hyprload6config14HyprloadConfigC1Ev+0x147) [0x7f63281449bf]
		??
		??:0
	#11 | /home/shadow/.local/share/hyprload/hyprload.so(_ZSt11make_uniqueIN8hyprload6config14HyprloadConfigEJEENSt8__detail9_MakeUniqIT_E15__single_objectEDpOT0_+0x2e) [0x7f6328199f5f]
		??
		??:0
	#12 | /home/shadow/.local/share/hyprload/hyprload.so(pluginInit+0xa2c) [0x7f632819776e]
		??
		??:0
	#13 | Hyprland(_ZN13CPluginSystem10loadPluginERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xabb) [0x55fbd42f4e4b]
		??
		??:0
	#14 | Hyprland(_Z14dispatchPluginNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x10f) [0x55fbd426438f]
		??
		??:0
	#15 | Hyprland(_Z8getReplyNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x5b7) [0x55fbd42657f7]
		??
		??:0
	#16 | Hyprland(_Z13hyprCtlFDTickijPv+0x100) [0x55fbd4266350]
		??
		??:0
	#17 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7f633e980ae2]
		??
		??:0
	#18 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7f633e9812d7]
		??
		??:0
	#19 | Hyprland(main+0x4b4) [0x55fbd41e6214]
		??
		??:0
	#20 | /usr/lib/libc.so.6(+0x23850) [0x7f633dd4c850]
		??
		??:0
	#21 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f633dd4c90a]
		??
		??:0
	#22 | Hyprland(_start+0x25) [0x55fbd41f4b85]
		??
		??:0


Log tail:
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:0 ~/.config/hypr/scripts/wall
[LOG] Process Created with pid 4858
[LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:0 /home/shadow/.local/share/hyprload/hyprload.sh
[LOG] Process Created with pid 4861
[LOG] ApplyConfigToKeyboard for "power-button", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Power Button"
[LOG] ApplyConfigToKeyboard for "asus-wireless-radio-control", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Asus Wireless Radio Control"
[LOG] ApplyConfigToKeyboard for "video-bus", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Video Bus"
[LOG] ApplyConfigToKeyboard for "video-bus-1", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Video Bus"
[LOG] ApplyConfigToKeyboard for "power-button-1", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Power Button"
[LOG] ApplyConfigToKeyboard for "sleep-button", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Sleep Button"
[LOG] ApplyConfigToKeyboard for "asus-wmi-hotkeys", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "Asus WMI hotkeys"
[LOG] ApplyConfigToKeyboard for "at-translated-set-2-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to us and variant to  for keyboard "AT Translated Set 2 keyboard"
[LOG] Applied config to mouse elan1203:00-04f3:307a-mouse, sens 0.00
[LOG] Applied config to mouse elan1203:00-04f3:307a-touchpad, sens 0.00
[LOG] Applying monitor rule for eDP-1
[LOG] Not applying a new rule to eDP-1 because it's already applied!
[LOG] Monitor eDP-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG]  [hookSystem] New hook event registered: render
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Framebuffer created, status 36053
[LOG] Allocated texture for BGTex
[LOG] Background created for monitor eDP-1
[LOG] Shaders initialized successfully.
[wlr] [backend/drm/drm.c:748] connector eDP-1: Modesetting with 1920x1080 @ 60.002 Hz
[LOG]  [hyprload] Hyprland version: {
    "branch": "main",
    "commit": "f2725a374a5921903bf918fdfd8111b537cbf18f",
    "dirty": true,
    "commit_message": "render: minor fixes to fullscreen rendering",
    "flags": []
}
[LOG]  [hyprload] Failed to parse config file: File could not be opened for reading
</blockquote></details>


[hyprlandCrashReport4796.txt](https://github.com/Duckonaut/hyprload/files/11454934/hyprlandCrashReport4796.txt)

**Comment by Duckonaut** [comment]
> > @shadowelite-sec i was having the same problem and just solved it by installing wlroots (for some reason I didn't have it)
> 
> Yes, the compilation was successful. However, when I try to run the `$HOME/.local/share/hyprload/hyprload.sh` , Hyprland crashes. (During the first launch of Hyprland, all plugins worked perfectly without any issues. )
> Crash Report
> 
> > --------------------------------------------
> >    Hyprland Crash Report
> > --------------------------------------------
> > Calm down, it was a misinput! MISINPUT!
> > Hyprland received signal 11 (Segmentation fault)
> > Version: f2725a374a5921903bf918fdfd8111b537cbf18f
> > Hyprland seems to be running with plugins. This crash might not be Hyprland's fault.
> > Plugins:
> > ()
> > System info:
> > System name: Linux
> > Node name: elite
> > Release: 6.3.1-arch2-1
> > Version: #1 SMP PREEMPT_DYNAMIC Wed, 10 May 2023 08:54:47 +0000
> > GPU:
> > 00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
> > 01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU117M [GeForce GTX 1650 Ti Mobile] [10de:1f95] (rev a1) (prog-if 00 [VGA controller])
> > os-release:
> > NAME="Arch Linux"
> > PRETTY_NAME="Arch Linux"
> > ID=arch
> > BUILD_ID=rolling
> > ANSI_COLOR="38;2;23;147;209"
> > HOME_URL="https://archlinux.org/"
> > DOCUMENTATION_URL="https://wiki.archlinux.org/"
> > SUPPORT_URL="https://bbs.archlinux.org/"
> > BUG_REPORT_URL="https://bugs.archlinux.org/"
> > PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
> > LOGO=archlinux-logo
> > Backtrace:
> > #0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x78e) [0x55fbd42590ee]
> > ??
> > ??:0
> > #1 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x55fbd41f4cdc]
> > ??
> > ??:0
> > #2 | /usr/lib/libc.so.6(+0x39ab0) [0x7f633dd62ab0]
> > ??
> > ??:0
> > #3 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNKSt8_Rb_treeIN4toml2v33keyESt4pairIKS2_St10unique_ptrINS1_4nodeESt14default_deleteIS6_EEESt10_Select1stISA_ESt4lessIvESaISA_EE8_M_beginEv+0xc) [0x7f632816641a]
> > ??
> > ??:0
> > #4 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNKSt8_Rb_treeIN4toml2v33keyESt4pairIKS2_St10unique_ptrINS1_4nodeESt14default_deleteIS6_EEESt10_Select1stISA_ESt4lessIvESaISA_EE17_M_lower_bound_trISt17basic_string_viewIcSt11char_traitsIcEEvEESt23_Rb_tree_const_iteratorISA_ERKT_+0x2c) [0x7f6328163ff2]
> > ??
> > ??:0
> > #5 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNKSt8_Rb_treeIN4toml2v33keyESt4pairIKS2_St10unique_ptrINS1_4nodeESt14default_deleteIS6_EEESt10_Select1stISA_ESt4lessIvESaISA_EE10_M_find_trISt17basic_string_viewIcSt11char_traitsIcEEvEESt23_Rb_tree_const_iteratorISA_ERKT_+0x33) [0x7f632816011b]
> > ??
> > ??:0
> > #6 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNSt8_Rb_treeIN4toml2v33keyESt4pairIKS2_St10unique_ptrINS1_4nodeESt14default_deleteIS6_EEESt10_Select1stISA_ESt4lessIvESaISA_EE10_M_find_trISt17basic_string_viewIcSt11char_traitsIcEEvEESt17_Rb_tree_iteratorISA_ERKT_+0x3a) [0x7f6328160062]
> > ??
> > ??:0
> > #7 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNSt3mapIN4toml2v33keyESt10unique_ptrINS1_4nodeESt14default_deleteIS4_EESt4lessIvESaISt4pairIKS2_S7_EEE4findISt17basic_string_viewIcSt11char_traitsIcEEEEDTcldtdtdefpT4_M_t10_M_find_trfp_EERKT_+0x23) [0x7f63281584e7]
> > ??
> > ??:0
> > #8 | /home/shadow/.local/share/hyprload/hyprload.so(_ZN4toml2v35table3getESt17basic_string_viewIcSt11char_traitsIcEE+0x46) [0x7f63281479ce]
> > ??
> > ??:0
> > #9 | /home/shadow/.local/share/hyprload/hyprload.so(_ZNK4toml2v35table8containsESt17basic_string_viewIcSt11char_traitsIcEE+0x5e) [0x7f6328146e3e]
> > ??
> > ??:0
> > #10 | /home/shadow/.local/share/hyprload/hyprload.so(_ZN8hyprload6config14HyprloadConfigC1Ev+0x147) [0x7f63281449bf]
> > ??
> > ??:0
> > #11 | /home/shadow/.local/share/hyprload/hyprload.so(_ZSt11make_uniqueIN8hyprload6config14HyprloadConfigEJEENSt8__detail9_MakeUniqIT_E15__single_objectEDpOT0_+0x2e) [0x7f6328199f5f]
> > ??
> > ??:0
> > #12 | /home/shadow/.local/share/hyprload/hyprload.so(pluginInit+0xa2c) [0x7f632819776e]
> > ??
> > ??:0
> > #13 | Hyprland(_ZN13CPluginSystem10loadPluginERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0xabb) [0x55fbd42f4e4b]
> > ??
> > ??:0
> > #14 | Hyprland(_Z14dispatchPluginNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x10f) [0x55fbd426438f]
> > ??
> > ??:0
> > #15 | Hyprland(_Z8getReplyNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x5b7) [0x55fbd42657f7]
> > ??
> > ??:0
> > #16 | Hyprland(_Z13hyprCtlFDTickijPv+0x100) [0x55fbd4266350]
> > ??
> > ??:0
> > #17 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7f633e980ae2]
> > ??
> > ??:0
> > #18 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7f633e9812d7]
> > ??
> > ??:0
> > #19 | Hyprland(main+0x4b4) [0x55fbd41e6214]
> > ??
> > ??:0
> > #20 | /usr/lib/libc.so.6(+0x23850) [0x7f633dd4c850]
> > ??
> > ??:0
> > #21 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f633dd4c90a]
> > ??
> > ??:0
> > #22 | Hyprland(_start+0x25) [0x55fbd41f4b85]
> > ??
> > ??:0
> > Log tail:
> > [LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:0 ~/.config/hypr/scripts/wall
> > [LOG] Process Created with pid 4858
> > [LOG] Executing WAYLAND_DISPLAY=wayland-1 DISPLAY=:0 /home/shadow/.local/share/hyprload/hyprload.sh
> > [LOG] Process Created with pid 4861
> > [LOG] ApplyConfigToKeyboard for "power-button", hasconfig: 0
> > [LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
> > [LOG] Set the keyboard layout to us and variant to  for keyboard "Power Button"
> > [LOG] ApplyConfigToKeyboard for "asus-wireless-radio-control", hasconfig: 0
> > [LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
> > [LOG] Set the keyboard layout to us and variant to  for keyboard "Asus Wireless Radio Control"
> > [LOG] ApplyConfigToKeyboard for "video-bus", hasconfig: 0
> > [LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
> > [LOG] Set the keyboard layout to us and variant to  for keyboard "Video Bus"
> > [LOG] ApplyConfigToKeyboard for "video-bus-1", hasconfig: 0
> > [LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
> > [LOG] Set the keyboard layout to us and variant to  for keyboard "Video Bus"
> > [LOG] ApplyConfigToKeyboard for "power-button-1", hasconfig: 0
> > [LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
> > [LOG] Set the keyboard layout to us and variant to  for keyboard "Power Button"
> > [LOG] ApplyConfigToKeyboard for "sleep-button", hasconfig: 0
> > [LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
> > [LOG] Set the keyboard layout to us and variant to  for keyboard "Sleep Button"
> > [LOG] ApplyConfigToKeyboard for "asus-wmi-hotkeys", hasconfig: 0
> > [LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
> > [LOG] Set the keyboard layout to us and variant to  for keyboard "Asus WMI hotkeys"
> > [LOG] ApplyConfigToKeyboard for "at-translated-set-2-keyboard", hasconfig: 0
> > [LOG] Attempting to create a keymap for layout us with variant  (rules: , model: , options: )
> > [LOG] Set the keyboard layout to us and variant to  for keyboard "AT Translated Set 2 keyboard"
> > [LOG] Applied config to mouse elan1203:00-04f3:307a-mouse, sens 0.00
> > [LOG] Applied config to mouse elan1203:00-04f3:307a-touchpad, sens 0.00
> > [LOG] Applying monitor rule for eDP-1
> > [LOG] Not applying a new rule to eDP-1 because it's already applied!
> > [LOG] Monitor eDP-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
> > [LOG]  [hookSystem] New hook event registered: render
> > [LOG] Framebuffer created, status 36053
> > [LOG] Framebuffer created, status 36053
> > [LOG] Framebuffer created, status 36053
> > [LOG] Framebuffer created, status 36053
> > [LOG] Allocated texture for BGTex
> > [LOG] Background created for monitor eDP-1
> > [LOG] Shaders initialized successfully.
> > [wlr] [backend/drm/drm.c:748] connector eDP-1: Modesetting with 1920x1080 @ 60.002 Hz
> > [LOG]  [hyprload] Hyprland version: {
> > "branch": "main",
> > "commit": "f2725a374a5921903bf918fdfd8111b537cbf18f",
> > "dirty": true,
> > "commit_message": "render: minor fixes to fullscreen rendering",
> > "flags": []
> > }
> > [LOG]  [hyprload] Failed to parse config file: File could not be opened for reading
> 
> [hyprlandCrashReport4796.txt](https://github.com/Duckonaut/hyprload/files/11454934/hyprlandCrashReport4796.txt)

please open a new issue about this. As for the original issue, it should be fixed in Hyprland - if you're running git, update Hyprland, uninstall wlroots and try the install script to confirm that the issue is solved

**Comment by shadowelite-sec** [comment]
The compilation issue has been fixed. Thank you so much 😄.

**Comment by CoachYT1** [comment]
I'm still having this issue with hyprland-nvidia-git r2901.896a78aa-1

**Comment by CoachYT1** [comment]
> > I'm still having this issue with hyprland-nvidia-git r2901.896a78aa-1
> 
> Me too, I suspect its just because hyprland-nvidia-git is a bit behind hyprland-git?

No, it's not. They're the same package but hyprland-nvidia-git has some patches to support nvidia.

**Comment by BvngeeCord** [comment]
> > > I'm still having this issue with hyprland-nvidia-git r2901.896a78aa-1
> > 
> > 
> > Me too, I suspect its just because hyprland-nvidia-git is a bit behind hyprland-git?
> 
> No, it's not. They're the same package but hyprland-nvidia-git has some patches to support nvidia.

Ah my misunderstanding. Well for now installing wlroots-git beforehand fixes compilation.
